# Generated by Django 3.1 on 2025-02-05 23:23

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerExercise',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'trainer_exercise',
            },
        ),
        migrations.CreateModel(
            name='TrainerRutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('dificultat', models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], default='Fácil', max_length=10)),
                ('energia', models.IntegerField(choices=[(3, 'Bajo'), (7, 'Medio'), (10, 'Alto')], default=7)),
                ('exercises', models.ManyToManyField(related_name='rutinas', to='trainer.TrainerExercise')),
            ],
            options={
                'db_table': 'rutines',
            },
        ),
    ]
