# Generated by Django 3.1 on 2025-02-03 15:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('tipus', models.CharField(choices=[('DIRIGIDA', 'Activitat Dirigida'), ('MUSCULACIO', 'Musculació')], default='DIRIGIDA', max_length=10)),
                ('durada_minuts', models.IntegerField()),
                ('capacitat_maxima', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('entrenador', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rutines',
            },
        ),
        migrations.CreateModel(
            name='SessioRutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inici', models.TimeField()),
                ('hora_fi', models.TimeField()),
                ('sala', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='sessions_inscrites', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.rutina')),
            ],
            options={
                'db_table': 'sessions_rutina',
                'unique_together': {('sala', 'data', 'hora_inici')},
            },
        ),
    ]
