# Generated by Django 3.1 on 2025-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20250206_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerrutina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
