# Generated by Django 3.1 on 2025-02-06 08:40

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20250206_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRutina',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('hora', models.IntegerField(choices=[(16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')])),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainerrutina')),
            ],
            options={
                'unique_together': {('dia', 'hora')},
            },
        ),
    ]
